name: Daily News Update

on:
  schedule:
    - cron: '0 0 * * *'  # 每天北京时间8点运行（UTC+8）
  workflow_dispatch:      # 允许手动触发
    inputs:
      time_mode:
        description: '时间模式选择'
        required: false
        default: 'default'
        type: choice
        options:
        - default     # 默认：获取昨天
        - past_days   # 获取过去N天
        - date_range  # 指定日期范围
      days:
        description: '获取过去几天的新闻（当选择past_days时）'
        required: false
        default: '7'
        type: string
      start_date:
        description: '开始日期 (YYYY-MM-DD，当选择date_range时)'
        required: false
        type: string
      end_date:
        description: '结束日期 (YYYY-MM-DD，当选择date_range时)'
        required: false
        type: string

jobs:
  update-news:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Debug OpenAI installation
      run: |
        python -c "import openai; print('OpenAI version:', openai.__version__)"
        python -c "from openai import OpenAI; print('OpenAI client imported successfully')"
    
    - name: Create .env file
      run: |
        echo "GPT_API_KEY=${{ secrets.GPT_API_KEY }}" > .env
        echo "GPT_BASE_URL=\"${{ secrets.GPT_BASE_URL }}\"" >> .env
        echo "SMTP_SERVER=\"${{ secrets.SMTP_SERVER }}\"" >> .env
        echo "SMTP_PORT=\"${{ secrets.SMTP_PORT }}\"" >> .env
        echo "SMTP_USERNAME=\"${{ secrets.SMTP_USERNAME }}\"" >> .env
        echo "SMTP_PASSWORD=\"${{ secrets.SMTP_PASSWORD }}\"" >> .env
        echo "SENDER_EMAIL=\"${{ secrets.SENDER_EMAIL }}\"" >> .env
        echo "RECEIVER_EMAIL=\"${{ secrets.RECEIVER_EMAIL }}\"" >> .env
    
    - name: Debug environment variables
      run: |
        echo "Environment variables created:"
        cat .env
    
    - name: Test OpenAI client initialization
      run: |
        python -c "
        import os
        from dotenv import load_dotenv
        from src.utils.gpt.config import GPTConfig
        from src.utils.gpt.helper import GPTHelper
        
        load_dotenv()
        print('Testing OpenAI client initialization...')
        try:
            config = GPTConfig()
            print('GPT Config created successfully')
            print('API Key exists:', bool(config.API_KEY))
            print('Base URL:', config.BASE_URL)
            
            helper = GPTHelper(config)
            print('GPTHelper created successfully')
        except Exception as e:
            print('Error details:')
            import traceback
            traceback.print_exc()
        "
    
    - name: Determine command arguments
      id: cmd_args
      run: |
        if [ "${{ github.event.inputs.time_mode }}" = "past_days" ]; then
          echo "args=all --days ${{ github.event.inputs.days }}" >> $GITHUB_OUTPUT
          echo "使用过去 ${{ github.event.inputs.days }} 天模式"
        elif [ "${{ github.event.inputs.time_mode }}" = "date_range" ]; then
          echo "args=all --date-range ${{ github.event.inputs.start_date }} ${{ github.event.inputs.end_date }}" >> $GITHUB_OUTPUT
          echo "使用日期范围模式: ${{ github.event.inputs.start_date }} 到 ${{ github.event.inputs.end_date }}"
        else
          echo "args=all" >> $GITHUB_OUTPUT
          echo "使用默认模式（获取昨天的新闻）"
        fi
    
    - name: Run news update
      run: python src/main.py ${{ steps.cmd_args.outputs.args }}
      
    - name: Cleanup
      run: python src/main.py cleanup 